services:
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: courseverse
      POSTGRES_PASSWORD: courseverse
      POSTGRES_DB: courseverse
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres

  courseverse:
    image: courseverse
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src
    environment:
      DATABASE_URI: postgresql://courseverse:courseverse@postgres:5432/courseverse
      SECRET_KEY: verysecretkey
    depends_on:
      postgres:
        condition: service_healthy
    container_name: courseverse

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - courseverse
    container_name: nginx